version: "2"
linters:
  default: standard
  enable:
    - misspell
    - unconvert
  settings:
    errcheck:
      exclude-functions:
        - (*encoding/json.Encoder).Encode
        - (io.Closer).Close
        - (*os.File).Close
        - (*database/sql.DB).Close
        - (*github.com/jackc/pgx/v5.Conn).Close
formatters:
  enable:
    - gofmt
