// Package seed loads db/seed/*.json (18 sample dealers from the approved mockup, generated by tools/seedgen)
// into PostgreSQL. Every write is an upsert keyed by the Odoo-shaped source id, so running it twice changes
// nothing, and a later Odoo sync of the same records updates them in place.
package seed

import (
	"context"
	"encoding/json"
	"fmt"
	"io/fs"
	"sort"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"distri-arc/internal/clock"
	"distri-arc/internal/store"
	"distri-arc/internal/store/gen"
)

const sourceSystem = "odoo"

type salesUser struct {
	Key      string `json:"key"`
	Name     string `json:"name"`
	Branch   string `json:"branch"`
	WANumber string `json:"wa_number"`
	Role     string `json:"role"`
	OdooUser int32  `json:"odoo_user_id"`
	Email    string `json:"email"`
}

type line struct {
	Product  string `json:"product"`
	Category string `json:"category"`
	Qty      int64  `json:"qty"`
	Price    int64  `json:"price"`
	Subtotal int64  `json:"subtotal"`
}

type order struct {
	OdooID      string     `json:"odoo_id"`
	Number      string     `json:"number"`
	State       string     `json:"state"`
	OrderedAt   time.Time  `json:"ordered_at"`
	ConfirmedAt time.Time  `json:"confirmed_at"`
	ShippedAt   time.Time  `json:"shipped_at"`
	InvoicedAt  time.Time  `json:"invoiced_at"`
	PaidAt      *time.Time `json:"paid_at"`
	Total       int64      `json:"total"`
	MarginPct   float64    `json:"margin_pct"`
	Lines       []line     `json:"lines"`
}

type invoice struct {
	OdooID   string  `json:"odoo_id"`
	Number   string  `json:"number"`
	Order    string  `json:"order"`
	IssuedAt string  `json:"issued_at"`
	DueAt    string  `json:"due_at"`
	Total    int64   `json:"total"`
	Paid     int64   `json:"paid"`
	PaidAt   *string `json:"paid_at"`
}

type payment struct {
	OdooID  string `json:"odoo_id"`
	Invoice string `json:"invoice"`
	PaidAt  string `json:"paid_at"`
	Amount  int64  `json:"amount"`
}

type contact struct {
	Key               string     `json:"key"`
	Name              string     `json:"name"`
	Role              string     `json:"role"`
	WANumber          string     `json:"wa_number"`
	IsPrimary         bool       `json:"is_primary"`
	Interactions90d   int32      `json:"interactions_90d"`
	LastInteractionAt *time.Time `json:"last_interaction_at"`
}

type commitment struct {
	Key     string  `json:"key"`
	Side    string  `json:"side"`
	Title   string  `json:"title"`
	Detail  string  `json:"detail"`
	Status  string  `json:"status"`
	DueAt   *string `json:"due_at"`
	Invoice string  `json:"invoice"`
}

type dealer struct {
	Slug        string    `json:"slug"`
	OdooID      string    `json:"odoo_id"`
	Name        string    `json:"name"`
	City        string    `json:"city"`
	Branch      string    `json:"branch"`
	Tier        string    `json:"tier"`
	SegmentDesc string    `json:"segment_desc"`
	Owner       string    `json:"owner"`
	CreditLimit int64     `json:"credit_limit"`
	TermsDays   int32     `json:"payment_terms_days"`
	Memo        string    `json:"memo"`
	Contacts    []contact `json:"contacts"`
	SOW         struct {
		Quarter string `json:"quarter"`
		SOW     int16  `json:"sow"`
		Note    string `json:"note"`
	} `json:"sow"`
	Orders      []order      `json:"orders"`
	Invoices    []invoice    `json:"invoices"`
	Payments    []payment    `json:"payments"`
	Commitments []commitment `json:"commitments"`
}

type signal struct {
	DedupeKey  string          `json:"dedupe_key"`
	Kind       string          `json:"kind"`
	Dealer     string          `json:"dealer"`
	Contact    string          `json:"contact"`
	Sales      string          `json:"sales"`
	OccurredAt time.Time       `json:"occurred_at"`
	Summary    string          `json:"summary"`
	Payload    json.RawMessage `json:"payload"`
}

type stockItem struct {
	OdooID         string  `json:"odoo_id"`
	Branch         string  `json:"branch"`
	SKU            string  `json:"sku"`
	Name           string  `json:"name"`
	Category       string  `json:"category"`
	Qty            int32   `json:"qty"`
	UnitCost       int64   `json:"unit_cost"`
	AgeDays        int32   `json:"age_days"`
	WeeklyVelocity float64 `json:"weekly_velocity"`
}

// Anchor is the date the sample data describes ("Senin, 5 Oktober 2026"); seeded source_write_date.
var Anchor = time.Date(2026, 10, 5, 6, 0, 0, 0, clock.WIB)

// Categories is the fixed product-mix list (01-glossary) with the Odoo category ids used by the sample data.
var Categories = []struct {
	OdooID int32
	Kat    string
}{{11, "Kamera & NVR"}, {12, "HDD & storage"}, {13, "Kabel & PoE"}, {14, "Modul LED"}, {15, "Fire alarm"}, {16, "Aksesoris"}}

// Result reports the row counts after seeding.
type Result = gen.CountSeededRow

// Run loads the seed files from fsys (normally db.Seed) in a single transaction.
func Run(ctx context.Context, s *store.Store, fsys fs.FS) (Result, error) {
	var sales []salesUser
	var dealers []dealer
	var signals []signal
	var stock []stockItem
	var policies map[string]json.RawMessage
	for name, dst := range map[string]any{"seed/sales.json": &sales, "seed/dealers.json": &dealers, "seed/signals.json": &signals, "seed/stock.json": &stock, "seed/policies.json": &policies} {
		b, err := fs.ReadFile(fsys, name)
		if err != nil {
			return Result{}, err
		}
		if err := json.Unmarshal(b, dst); err != nil {
			return Result{}, fmt.Errorf("%s: %w", name, err)
		}
	}

	err := s.Tx(ctx, func(q *gen.Queries, _ pgx.Tx) error {
		ss := sourceSystem
		salesID := map[string]uuid.UUID{}
		for _, u := range sales {
			sid := fmt.Sprintf("res.users:%d", u.OdooUser)
			id, err := q.UpsertSalesUser(ctx, gen.UpsertSalesUserParams{Name: u.Name, Branch: u.Branch, WaNumber: &u.WANumber, OdooUserID: &u.OdooUser, Role: u.Role, SourceSystem: &ss, SourceID: &sid})
			if err != nil {
				return fmt.Errorf("sales %s: %w", u.Key, err)
			}
			salesID[u.Key] = id
			role := u.Role
			if _, err := q.UpsertUser(ctx, gen.UpsertUserParams{Email: &u.Email, Name: &u.Name, Role: &role, SalesUserID: &id}); err != nil {
				return err
			}
		}
		for _, c := range Categories {
			if err := q.UpsertCategoryMap(ctx, gen.UpsertCategoryMapParams{OdooCategoryID: c.OdooID, Kat: c.Kat}); err != nil {
				return err
			}
		}

		dealerID := map[string]uuid.UUID{}
		contactID := map[string]uuid.UUID{}
		for _, d := range dealers {
			owner := salesID[d.Owner]
			wd := Anchor
			memoAt := Anchor
			id, err := q.UpsertDealer(ctx, gen.UpsertDealerParams{
				Slug: &d.Slug, Name: d.Name, City: &d.City, Branch: d.Branch, Tier: &d.Tier, SegmentDesc: &d.SegmentDesc,
				OwnerID: &owner, CreditLimit: d.CreditLimit, PaymentTermsDays: d.TermsDays,
				SourceSystem: &ss, SourceID: &d.OdooID, SourceWriteDate: &wd, Memo: &d.Memo, MemoUpdatedAt: &memoAt,
			})
			if err != nil {
				return fmt.Errorf("dealer %s: %w", d.Slug, err)
			}
			dealerID[d.Slug] = id
			for _, c := range d.Contacts {
				sid := "res.partner.contact:" + c.Key
				cid, err := q.UpsertContact(ctx, gen.UpsertContactParams{DealerID: &id, Name: &c.Name, Role: &c.Role, WaNumber: &c.WANumber, IsPrimary: c.IsPrimary, LastInteractionAt: c.LastInteractionAt, Interactions90d: c.Interactions90d, SourceSystem: &ss, SourceID: &sid})
				if err != nil {
					return fmt.Errorf("contact %s: %w", c.Key, err)
				}
				contactID[c.Key] = cid
			}
			note := d.SOW.Note
			if err := q.UpsertSowEstimate(ctx, gen.UpsertSowEstimateParams{DealerID: &id, Quarter: d.SOW.Quarter, Sow: d.SOW.SOW, Note: &note, ConfirmedBy: &owner, ConfirmedAt: Anchor.AddDate(0, 0, -20)}); err != nil {
				return err
			}
			orderID := map[string]uuid.UUID{}
			for _, o := range d.Orders {
				lines, _ := json.Marshal(o.Lines)
				ca, sa, ia := o.ConfirmedAt, o.ShippedAt, o.InvoicedAt
				oa := o.OrderedAt
				oid, err := q.UpsertOrder(ctx, gen.UpsertOrderParams{
					DealerID: &id, Number: &o.Number, State: o.State, OrderedAt: &oa, ConfirmedAt: &ca, ShippedAt: &sa, InvoicedAt: &ia, PaidAt: o.PaidAt,
					Total: o.Total, MarginPct: &o.MarginPct, Lines: lines, CreatedBy: "odoo", SourceSystem: &ss, SourceID: &o.OdooID, SourceWriteDate: &wd,
				})
				if err != nil {
					return fmt.Errorf("order %s: %w", o.Number, err)
				}
				orderID[o.Number] = oid
			}
			invID := map[string]uuid.UUID{}
			for _, inv := range d.Invoices {
				oid := orderID[inv.Order]
				issued, due := date(inv.IssuedAt), date(inv.DueAt)
				var paidAt *time.Time
				if inv.PaidAt != nil {
					t := date(*inv.PaidAt)
					paidAt = &t
				}
				iid, err := q.UpsertInvoice(ctx, gen.UpsertInvoiceParams{DealerID: &id, OrderID: &oid, Number: &inv.Number, IssuedAt: &issued, DueAt: &due, Total: inv.Total, Paid: inv.Paid, PaidAt: paidAt, State: "posted", SourceSystem: &ss, SourceID: &inv.OdooID, SourceWriteDate: &wd})
				if err != nil {
					return fmt.Errorf("invoice %s: %w", inv.Number, err)
				}
				invID[inv.Number] = iid
			}
			for _, p := range d.Payments {
				iid := invID[p.Invoice]
				pa := date(p.PaidAt)
				if err := q.UpsertPayment(ctx, gen.UpsertPaymentParams{DealerID: &id, InvoiceID: &iid, PaidAt: &pa, Amount: p.Amount, SourceSystem: &ss, SourceID: &p.OdooID}); err != nil {
					return err
				}
			}
			for _, c := range d.Commitments {
				var due *time.Time
				if c.DueAt != nil {
					t := date(*c.DueAt)
					due = &t
				}
				var iid *uuid.UUID
				if v, ok := invID[c.Invoice]; ok {
					iid = &v
				}
				key, detail := c.Key, c.Detail
				if err := q.UpsertCommitment(ctx, gen.UpsertCommitmentParams{DealerID: &id, Side: c.Side, Title: c.Title, Detail: &detail, Status: c.Status, DueAt: due, InvoiceID: iid, SourceKey: &key}); err != nil {
					return err
				}
			}
		}

		for _, it := range stock {
			src := it.OdooID
			if err := q.UpsertStockItem(ctx, gen.UpsertStockItemParams{Branch: it.Branch, Sku: it.SKU, Name: it.Name, Category: it.Category, Qty: it.Qty, UnitCost: it.UnitCost, Value: int64(it.Qty) * it.UnitCost, AgeDays: it.AgeDays, WeeklyVelocity: it.WeeklyVelocity, SourceSystem: &ss, SourceID: &src, SourceWriteDate: &Anchor}); err != nil {
				return fmt.Errorf("stock %s: %w", it.SKU, err)
			}
		}

		memo := map[uuid.UUID][]uuid.UUID{}
		for _, sg := range signals {
			p := gen.UpsertSignalParams{Kind: sg.Kind, OccurredAt: sg.OccurredAt, DedupeKey: sg.DedupeKey, Payload: sg.Payload}
			summary := sg.Summary
			p.Summary = &summary
			if v, ok := dealerID[sg.Dealer]; ok {
				p.DealerID = &v
			}
			if v, ok := contactID[sg.Contact]; ok {
				p.ContactID = &v
			}
			if v, ok := salesID[sg.Sales]; ok {
				p.SalesID = &v
			}
			sid, err := q.UpsertSignal(ctx, p)
			if err != nil {
				return fmt.Errorf("signal %s: %w", sg.DedupeKey, err)
			}
			if p.DealerID != nil && isTimeline(sg.DedupeKey) {
				memo[*p.DealerID] = append(memo[*p.DealerID], sid)
			}
		}
		for did, ids := range memo {
			if err := q.SetDealerMemoSignals(ctx, gen.SetDealerMemoSignalsParams{ID: did, MemoSignalIds: ids}); err != nil {
				return err
			}
		}

		keys := make([]string, 0, len(policies))
		for k := range policies {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			if err := q.InsertPolicyIfMissing(ctx, gen.InsertPolicyIfMissingParams{Key: k, Value: policies[k]}); err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		return Result{}, err
	}
	return s.Q.CountSeeded(ctx)
}

func isTimeline(key string) bool { return len(key) > 14 && key[:14] == "seed:timeline:" }

func date(s string) time.Time {
	t, err := time.ParseInLocation("2006-01-02", s, clock.WIB)
	if err != nil {
		panic(err)
	}
	return t
}
